# ----------------------------------------------------
# Name: Lezar - Beauty Salon & Spa Jekyll Theme
# Version: 1.0
# Author: Robert_Biswas
# Author URL: 'https://themeforest.net/user/robert_biswas'
# Demo URL: 'https://preview.robertbiswas.com/jekyll/lezar/'
# Copyright © Lezar by robert_biswas. All Rights Reserved.
#
# ----------------------------------------------------
title: Lezar - Beauty Salon and Spa Jekyll Theme
theme_version: 1.0.0
baseurl: 'philosophyhairsalon-com.github.io' # the subpath or subdomain of your site, e.g. /blog
url: '/philosophyhairsalon-com.github.io' # the base hostname & protocol for your site, e.g. http://yourdomain.com

# paginations & permalinks
paginate: 5
paginate_path: "/blog/page:num/"
permalink: pretty

sass:
  sass_dir: _sass
  style: compressed

# archives
jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: archive
    tag: archive
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/

markdown: kramdown
# Build settings
plugins:
  - jekyll-archives
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-coffeescript

# Author Bio to show in Blog Sidebar
author_bio:
  name: "Robert Biswas"
  image: "assets/images/widgets/about-author.jpg"
  desc: "On the other hand, we denounce with righteous indignation and dislike men who beguiled"